name: Send email daily at 4am Sydney time

on:
  schedule:
    # Runs daily at 4am Sydney time (17:00 UTC, accounting for AEDT UTC+11)
    # During daylight saving (Oct-Apr): 4am AEDT = 17:00 UTC previous day
    # During standard time (Apr-Oct): 4am AEST = 18:00 UTC previous day
    # Using 17:00 UTC as the primary schedule (AEDT)
    - cron: '0 17 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Send email
        env:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          SMTP_FROM: ${{ secrets.GMAIL_USERNAME }}
          SMTP_USE_TLS: true
        run: |
          python -V
          python main.py